name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run build
        run: |
          echo "old GITHUB_REF is ${{ github.ref }}"
          GITHUB_REF=$(echo ${{ github.ref }} | sed -e "s#refs/heads##g")
          echo "new GITHUB_REF is ${{ GITHUB_REF }}"
