name: ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Wait for Previous Deployment
        uses: softprops/turnstyle@v1
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          # add sleep for wait check
          sleep 90
      - name: populate environment
        run: |
          echo "::set-env name=CI::\"github\""
          echo "::set-env name=BUILD_NUMBER::${{ github.run_id }}"
      - name: add ${{ runner.OS }} specific variable
        run: |
          if ${{ runner.OS }} == "Linux"
          then
            echo "linux operations"
            echo "::set-env name=OS_VAR::linux"
          elif ${{ runner.OS }} == "macOS "
            echo "macOS operations"
            echo "::set-env name=OS_VAR::macOS"
          fi
      - name: run build
        run: |
          echo "::set-env name=GITHUB_REF::${{ github.ref }}"
          echo "old GITHUB_REF is $GITHUB_REF"
          GITHUB_REF=$(echo $GITHUB_REF | sed -e "s#refs/heads/##g")
          echo "new GITHUB_REF is $GITHUB_REF"
      - name: display environment
        run: |
          echo "CI is $CI"
          echo "Build number is $BUILD_NUMBER"
          echo "OS_VAR is $OS_VAR"
