name: aws credentials flow

# only trigger on demand
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@a283f9441d2d96eb62436dc46d7014f5d357ac22 # v3
      - name: Write into file
        id: write_file
        uses: timheuer/base64-to-file@88f7f51ef20bad84d7b50fedaf2eab2245b39a95 # v1.2
        with:
          fileName: 'myTemporaryFile.txt'
          encodedString: ${{ secrets.AWS_CREDENTIALS_FILE_BASE64 }}

      - name: Use the output
        run: |
          ls ${{ steps.write_file.outputs.filePath }}
          cat ${{ steps.write_file.outputs.filePath }}
