name: hurl

on:
  push:
    branches:
      - main
    paths:
      - hurl/**
      - .github/workflows/hurl.yml
  workflow_dispatch:
  schedule:
    # run every 30 mins
    - cron: "*/30 * * * *"

jobs:
  hurl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install hurl
        run: |
          cd /usr/local/bin && curl -fsSL https://github.com/Orange-OpenSource/hurl/releases/download/$HURL_VERSION/hurl-$HURL_VERSION-x86_64-linux.tar.gz | sudo tar xz --strip-components 1
          hurl --version
        env:
          HURL_VERSION: 4.0.0

      - name: Run tests
        run: hurl --retry --retry-max-count 5 --test --glob "hurl/chenrui.dev/site.hurl"
