name: lang-go

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lang-go.yml'

permissions:
  contents: read

jobs:
  show-go-version:
    name: Show Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.22, 1.23, 1.24]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Display Go Version
        run: go version
