name: repository-dispatch

on:
  repository_dispatch:
    types: ["trigger-event"]

# how to test this workflow
# $ curl -X POST -u "chenrui333:${GITHUB_ACTION_REPO_TOKEN}" \
# -H "Accept: application/vnd.github.everest-preview+json"  \
# -H "Content-Type: application/json" \
# https://api.github.com/repos/chenrui333/github-action-test/dispatches \
# --data '{"event_type":"trigger-event","client_payload":{"id":1, "unit":false,"integration":true}}'

# run log result
# https://github.com/chenrui333/github-action-test/actions/runs/161112535

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: show context
        run: |
          echo "github sha is ${{ github.sha }}"
          echo "github.event is ${{ toJson(github.event) }}"
          echo "github.event_name is ${{ github.event_name }}"
      - name: populate environment
        run: |
          echo "::set-env name=ID::${{ github.event.client_payload.id }}"
      - name: run build
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "id is $ID"
          echo "integration is ${{ github.event.client_payload.integration }}"
