name: repository-dispatch

on:
  repository_dispatch:
    types: ["trigger-event"]

# how to test this workflow
# GITHUB_TOKEN=xxx ./scripts/repository-dispatch-trigger.sh

# run log result
# https://github.com/chenrui333/github-action-test/actions/runs/161112535

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: show context
        run: |
          echo "github sha is ${{ github.sha }}"
          echo "github.event is ${{ toJson(github.event) }}"
          echo "github.event_name is ${{ github.event_name }}"
      - name: populate environment
        run: |
          echo "::set-env name=ID::${{ github.event.client_payload.id }}"
      - name: run build
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "id is $ID"
          echo "integration is ${{ github.event.client_payload.integration }}"
  show-id:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: show id
        run: |
          echo "test environment ID used cross jobs"
          echo "id is $ID"
