# https://github.com/github/super-linter
name: super-linter

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for Previous Deployment
        uses: softprops/turnstyle@v1
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
